# Generated by Django 4.2.14 on 2024-09-28 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_gender', models.CharField(choices=[('male', 'Homme'), ('female', 'Femme')], max_length=6)),
                ('choices_gender', models.CharField(blank=True, choices=[('female', 'Femme'), ('male', 'Homme'), ('non_binary', 'Non binaire'), ('other', 'Autre'), ('not_to_say', 'Je préfère ne pas répondre')], max_length=30)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Inconnu')], max_length=7)),
                ('role', models.CharField(choices=[('new', 'Nouveau'), ('freelance', 'Freelance'), ('member', 'Membre'), ('staff', 'Staff')], default='new', max_length=10)),
                ('avatar', models.ImageField(default='../static/images/profil_default.png', upload_to='clients/avatars')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('nom', models.CharField(blank=True, max_length=30)),
                ('prenom', models.CharField(blank=True, max_length=30)),
                ('tel', models.CharField(blank=True, max_length=10)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
