# Generated by Django 4.2.14 on 2024-09-28 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.SlugField(unique=True)),
                ('nom_propre', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('adresse_postale', models.CharField(max_length=255)),
                ('coordonnees_gps', models.CharField(max_length=50)),
                ('description_publique', models.TextField(blank=True, null=True)),
                ('taille', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RepliqueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('Partie', 'Partie'), ('Evenement', 'Evenement')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_heure', models.DateTimeField()),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('nb_joueurs_max', models.PositiveIntegerField()),
                ('nb_joueurs_min', models.PositiveIntegerField()),
                ('freelance', models.BooleanField(default=False)),
                ('locations', models.BooleanField(default=False)),
                ('repas', models.BooleanField(default=False)),
                ('prix_freelance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prix_location', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('prix_repas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('limite_aeg', models.IntegerField(default=0)),
                ('limite_smg', models.IntegerField(default=0)),
                ('limite_pa', models.IntegerField(default=0)),
                ('limite_pompe', models.IntegerField(default=0)),
                ('limite_mg', models.IntegerField(default=0)),
                ('limite_dmr', models.IntegerField(default=0)),
                ('limite_autre', models.IntegerField(default=0)),
                ('type_replique_autorisee', models.CharField(blank=True, max_length=200)),
                ('puissance_max_joule', models.PositiveIntegerField(default=2)),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evenement.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repas', models.BooleanField(default=False)),
                ('location', models.BooleanField(default=False)),
                ('besoin_covoiturage', models.BooleanField(default=False)),
                ('offre_covoiturage', models.BooleanField(default=False)),
                ('accepte_regles', models.BooleanField(default=False)),
                ('nom_ami', models.CharField(blank=True, max_length=100)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('paiement_valide', models.BooleanField(default=False)),
                ('chrony_valide', models.BooleanField(default=False)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.evenement')),
                ('inscrit_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_faites', to=settings.AUTH_USER_MODEL)),
                ('repliques', models.ManyToManyField(blank=True, to='gun.gun')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'evenement', 'nom_ami')},
            },
        ),
    ]
