# Generated by Django 4.2.14 on 2024-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0003_inscription_montant_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='amis_repliques',
        ),
        migrations.AddField(
            model_name='inscription',
            name='amis_repliques',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
