# Generated by Django 4.2.14 on 2024-09-28 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replica_type', models.CharField(choices=[('AEG', 'AEG'), ('SMG', 'SMG'), ('PA', 'PA'), ('POMPE', 'POMPE'), ('MG', 'MG'), ('DMR', 'DMR'), ('AUTRE', 'AUTRE')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('joule', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_joule_update', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/gun')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réplique',
            },
        ),
    ]
